# Generated by Django 4.2.16 on 2024-11-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raw_weight', models.FloatField(help_text='Вес сырого ингредиента в граммах')),
                ('cooked_weight', models.FloatField(blank=True, help_text='Вес приготовленного ингредиента в граммах', null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Стоимость ингредиента в рублях', max_digits=7)),
                ('cooking_time', models.IntegerField(blank=True, help_text='Время приготовления в минутах', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, help_text='Количество ингредиента в рецепте')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe_catalog.RecipeIngredient', to='recipe_catalog.ingredient'),
        ),
    ]
