# Generated by Django 4.2.16 on 2024-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0002_recipeingredient_unique_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'грамм'), ('tbsp', 'столовая ложка'), ('cup', 'стакан'), ('tsp', 'чайная ложка'), ('piece', 'штука')], default='g', help_text='Единица измерения ингредиента', max_length=10),
        ),
    ]
