# Generated by Django 4.2.16 on 2024-11-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0004_unit_remove_recipeingredient_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='conversion_to_grams',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения для этого количества', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_catalog.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='gram_equivalent',
            field=models.FloatField(help_text='Эквивалент в граммах для данной единицы измерения', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cooked_weight',
            field=models.FloatField(blank=True, help_text='Вес приготовленного ингредиента в граммах', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cooking_time',
            field=models.IntegerField(blank=True, help_text='Время приготовления в минутах', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость ингредиента в рублях', max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='raw_weight',
            field=models.FloatField(help_text='Вес сырого ингредиента в граммах'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения для ингредиента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_catalog.unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe_catalog.RecipeIngredient', to='recipe_catalog.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=1, help_text='Количество ингредиента в рецепте'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
