# Generated by Django 4.2.16 on 2024-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0006_unit_default_cooked_weight_unit_default_raw_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='default_cooked_weight',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='default_raw_weight',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='raw_weight',
            field=models.FloatField(help_text='Вес сырого ингредиента в граммах', null=True),
        ),
    ]
